name: Java CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build TNE Core
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
           mkdir ~/.m2
           echo "<settings><servers><server><id>github</id><username>TheNewEconomy</username><password>${GITHUB_TOKEN}</password></server><server><id>githubTowny</id><username>TheNewEconomy</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
           mvn package --file TNE/pom.xml
    - name: Build Conversion Module
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
           mkdir ~/.m2
           echo "<settings><servers><server><id>github</id><username>TheNewEconomy</username><password>${GITHUB_TOKEN}</password></server><server><id>githubTowny</id><username>TheNewEconomy</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xm
           mvn package --file TNEConversion/pom.xml
    - name: Build Signs Module
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
           mkdir ~/.m2
           echo "<settings><servers><server><id>github</id><username>TheNewEconomy</username><password>${GITHUB_TOKEN}</password></server><server><id>githubTowny</id><username>TheNewEconomy</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xm
           mvn package --file TNESigns/pom.xml
    - name: Build Mobs Module
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
           mkdir ~/.m2
           echo "<settings><servers><server><id>github</id><username>TheNewEconomy</username><password>${GITHUB_TOKEN}</password></server><server><id>githubTowny</id><username>TheNewEconomy</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xm
           mvn package --file TNEMobs/pom.xml
